plugins: discogs replaygain smartplaylist zero acousticbrainz types fetchart copyartifacts check duplicates
directory: ~/music
library: ~/.beets.blb
original_date: yes
replaygain:
    backend: bs1770gain
    overwrite: yes

paths:
    default: $albumartist/$album%aunique{}/$track $title

smartplaylist:
    relative_to: ~/music
    playlist_dir: ~/playlists
    playlists:
        - name: 'Blue Note Records.m3u'
          query: 'label:"Blue Note"'
        - name: New.m3u
          query: 'added+'

zero:
    fields: [artist_sort,  albumartist_sort]
    update_database: true

types:
    mood_relaxed: float
    bpm: int
    mood_acoustic: float
    mood_happy: float
    mood_sad: float

fetchart:
    google_key:  AIzaSyBJSJdwjvdfjJ9PJ0gAa2cssAHBWqRwN4s
    sources: filesystem coverart itunes amazon albumart google fanarttv
    fanarttv_key: 7ae9efc470e11c7750b5e1746776a088

paths:
    ext:log: $albumpath/$artist - $album
    ext:cue: $albumpath/$artist - $album

copyartifacts:
    extensions: .cue .log .txt
    print_ignored: yes
