plugins: smartplaylist replaygain importfeeds lastgenre inline zero missing extrafiles fetchart badfiles scrub
directory: ~/music
library: ~/.beets.blb
original_date: yes
replaygain:
    backend: bs1770gain
    overwrite: yes


smartplaylist:
    relative_to: ~/music
    playlist_dir: ~/playlists
    playlists:
      - name: 'Blue Note Records: Golden Years.m3u'
        query: 'label:"Blue Note" year:1950..1966'

item_fields:
    disc_and_track: u'%02i.%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)
    path_artist: albumartist_sort or albumartist

paths:
    default: $path_artist/$album/$disc_and_track $title
    ext:log: $albumpath/$artist - $album
    ext:cue: $albumpath/$artist - $album

check:
    import: no
    threads: 4

importfeeds:
    dir: ~/playlists
    formats: m3u
    relative_to: ~/music/    

lastgenre:
    count: 2

zero:
    fields: images

extrafiles:
    patterns:
      all: 
        - '*.cue'
        - '*.log'
        - '*.txt'
        - '*.jpg'

fetchart:
    sources: filesystem

badfiles:
    commands:
        flac: flac --test --warnings-as-errors --silent
