plugins: discogs replaygain smartplaylist fetchart mbsync importfeeds lastgenre inline
directory: ~/music
library: ~/.beets.blb
original_date: yes
replaygain:
    backend: bs1770gain
    overwrite: yes


smartplaylist:
    relative_to: ~/music
    playlist_dir: ~/playlists
    playlists:
      - name: 'Blue Note Records: Golden Years.m3u'
        query: 'label:"Blue Note" year:1950..1966'

fetchart:
    sources: filesystem coverart itunes amazon albumart fanarttv wikipedia google

item_fields:
    initial: albumartist[0].upper() + u'.'
    disc_and_track: u'%02i.%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)

paths:
    default: $albumartist/$album/$disc_and_track $title
    ext:log: $albumpath/$artist - $album
    ext:cue: $albumpath/$artist - $album

check:
    import: no
    threads: 4

importfeeds:
    dir: ~/playlists
    formats: m3u
    relative_to: ~/music/    

lastgenre:
    count: 2
