plugins: importfeeds lastgenre inline zero missing extrafiles fetchart badfiles info discogs_extradata tagsplit

directory: ~/music_import
library: ~/music_import/beets.db

original_date: yes

replaygain:
    backend: bs1770gain
    overwrite: yes


item_fields:
    disc_and_track: u'%02i.%02i' % (disc, track) if
                    disctotal > 1 else u'%02i' % (track)
    path_artist: albumartist_sort or albumartist

paths:
    default: $path_artist/$album/$disc_and_track $title
    ext:log: $albumpath/$artist - $album
    ext:cue: $albumpath/$artist - $album

check:
    import: no
    threads: 4

lastgenre:
    count: 3
    separator: '|'

zero:
    fields: images

extrafiles:
    patterns:
      all:
        - '*.cue'
        - '*.log'
        - '*.txt'
        - '*.jpg'

fetchart:
    sources: filesystem

badfiles:
    commands:
        flac: flac --test --silent

tagsplit:
    separator: '|'
    fields:
        - genre
        - label
        - performer

discogs_extradata:
    separator: '|'
    token: ''
